//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.14 at 05:38:42 PM CEST 
//


package eu.transkribus.core.model.beans.pagecontent;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CellCoordsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CellCoordsType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schema.primaresearch.org/PAGE/gts/pagecontent/2013-07-15}CoordsType">
 *       &lt;attribute name="cornerPts" type="{http://schema.primaresearch.org/PAGE/gts/pagecontent/2013-07-15}CornerPointsType" default="0 1 2 3" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CellCoordsType")
public class CellCoordsType
    extends CoordsType
{

    @XmlAttribute(name = "cornerPts")
    protected String cornerPts;

    /**
     * Gets the value of the cornerPts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCornerPts() {
        if (cornerPts == null) {
            return "0 1 2 3";
        } else {
            return cornerPts;
        }
    }

    /**
     * Sets the value of the cornerPts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCornerPts(String value) {
        this.cornerPts = value;
    }

}
