//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.16 at 03:51:41 PM CEST 
//


package eu.transkribus.core.model.beans.pagecontent;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ChartTypeSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ChartTypeSimpleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="bar"/>
 *     &lt;enumeration value="line"/>
 *     &lt;enumeration value="pie"/>
 *     &lt;enumeration value="scatter"/>
 *     &lt;enumeration value="surface"/>
 *     &lt;enumeration value="other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ChartTypeSimpleType")
@XmlEnum
public enum ChartTypeSimpleType {

    @XmlEnumValue("bar")
    BAR("bar"),
    @XmlEnumValue("line")
    LINE("line"),
    @XmlEnumValue("pie")
    PIE("pie"),
    @XmlEnumValue("scatter")
    SCATTER("scatter"),
    @XmlEnumValue("surface")
    SURFACE("surface"),
    @XmlEnumValue("other")
    OTHER("other");
    private final String value;

    ChartTypeSimpleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ChartTypeSimpleType fromValue(String v) {
        for (ChartTypeSimpleType c: ChartTypeSimpleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
