//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.23 at 05:32:05 PM MEZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schema.primaresearch.org/PAGE/gts/pagecontent/2013-07-15", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package eu.transkribus.core.model.beans.pagecontent;
