//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 10:00:29 PM CEST 
//


package eu.transkribus.core.model.beans.pagecontent;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Definition of the reading order within the page. To express a reading order between elements they have to be included in an OrderedGroup. Groups may contain further groups.
 * 
 * <p>Java class for ReadingOrderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReadingOrderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="OrderedGroup" type="{http://schema.primaresearch.org/PAGE/gts/pagecontent/2013-07-15}OrderedGroupType"/>
 *         &lt;element name="UnorderedGroup" type="{http://schema.primaresearch.org/PAGE/gts/pagecontent/2013-07-15}UnorderedGroupType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReadingOrderType", propOrder = {
    "orderedGroup",
    "unorderedGroup"
})
public class ReadingOrderType {

    @XmlElement(name = "OrderedGroup")
    protected OrderedGroupType orderedGroup;
    @XmlElement(name = "UnorderedGroup")
    protected UnorderedGroupType unorderedGroup;

    /**
     * Gets the value of the orderedGroup property.
     * 
     * @return
     *     possible object is
     *     {@link OrderedGroupType }
     *     
     */
    public OrderedGroupType getOrderedGroup() {
        return orderedGroup;
    }

    /**
     * Sets the value of the orderedGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderedGroupType }
     *     
     */
    public void setOrderedGroup(OrderedGroupType value) {
        this.orderedGroup = value;
    }

    /**
     * Gets the value of the unorderedGroup property.
     * 
     * @return
     *     possible object is
     *     {@link UnorderedGroupType }
     *     
     */
    public UnorderedGroupType getUnorderedGroup() {
        return unorderedGroup;
    }

    /**
     * Sets the value of the unorderedGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnorderedGroupType }
     *     
     */
    public void setUnorderedGroup(UnorderedGroupType value) {
        this.unorderedGroup = value;
    }

}
