//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.09 at 03:38:19 PM CET 
//


package eu.transkribus.core.model.beans.pagecontent;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ScriptSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ScriptSimpleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Arabic"/>
 *     &lt;enumeration value="Bengali"/>
 *     &lt;enumeration value="Chinese-simplified"/>
 *     &lt;enumeration value="Chinese-traditional"/>
 *     &lt;enumeration value="Cyrillic"/>
 *     &lt;enumeration value="Devangari"/>
 *     &lt;enumeration value="Ethiopic"/>
 *     &lt;enumeration value="Greek"/>
 *     &lt;enumeration value="Gujarati"/>
 *     &lt;enumeration value="Gurmukhi"/>
 *     &lt;enumeration value="Hebrew"/>
 *     &lt;enumeration value="Latin"/>
 *     &lt;enumeration value="Thai"/>
 *     &lt;enumeration value="other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ScriptSimpleType")
@XmlEnum
public enum ScriptSimpleType {

    @XmlEnumValue("Arabic")
    ARABIC("Arabic"),
    @XmlEnumValue("Bengali")
    BENGALI("Bengali"),
    @XmlEnumValue("Chinese-simplified")
    CHINESE_SIMPLIFIED("Chinese-simplified"),
    @XmlEnumValue("Chinese-traditional")
    CHINESE_TRADITIONAL("Chinese-traditional"),
    @XmlEnumValue("Cyrillic")
    CYRILLIC("Cyrillic"),
    @XmlEnumValue("Devangari")
    DEVANGARI("Devangari"),
    @XmlEnumValue("Ethiopic")
    ETHIOPIC("Ethiopic"),
    @XmlEnumValue("Greek")
    GREEK("Greek"),
    @XmlEnumValue("Gujarati")
    GUJARATI("Gujarati"),
    @XmlEnumValue("Gurmukhi")
    GURMUKHI("Gurmukhi"),
    @XmlEnumValue("Hebrew")
    HEBREW("Hebrew"),
    @XmlEnumValue("Latin")
    LATIN("Latin"),
    @XmlEnumValue("Thai")
    THAI("Thai"),
    @XmlEnumValue("other")
    OTHER("other");
    private final String value;

    ScriptSimpleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ScriptSimpleType fromValue(String v) {
        for (ScriptSimpleType c: ScriptSimpleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
