//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.14 at 05:38:42 PM CEST 
//


package eu.transkribus.core.model.beans.pagecontent;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import eu.transkribus.core.model.beans.pagecontent_trp.TrpTextRegionType;


/**
 * A single cell of a table
 * 
 * <p>Java class for TableCellType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TableCellType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schema.primaresearch.org/PAGE/gts/pagecontent/2013-07-15}TextRegionType">
 *       &lt;sequence>
 *         &lt;element name="CornerPts" type="{http://schema.primaresearch.org/PAGE/gts/pagecontent/2013-07-15}CornerPointsType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="row" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="col" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="rowSpan" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
 *       &lt;attribute name="colSpan" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TableCellType", propOrder = {
    "cornerPts"
})
public class TableCellType
    extends TrpTextRegionType
{

    @XmlElement(name = "CornerPts", required = true, defaultValue = "0 1 2 3")
    protected String cornerPts;
    @XmlAttribute(name = "row", required = true)
    protected int row;
    @XmlAttribute(name = "col", required = true)
    protected int col;
    @XmlAttribute(name = "rowSpan")
    protected Integer rowSpan;
    @XmlAttribute(name = "colSpan")
    protected Integer colSpan;

    /**
     * Gets the value of the cornerPts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCornerPts() {
        return cornerPts;
    }

    /**
     * Sets the value of the cornerPts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCornerPts(String value) {
        this.cornerPts = value;
    }

    /**
     * Gets the value of the row property.
     * 
     */
    public int getRow() {
        return row;
    }

    /**
     * Sets the value of the row property.
     * 
     */
    public void setRow(int value) {
        this.row = value;
    }

    /**
     * Gets the value of the col property.
     * 
     */
    public int getCol() {
        return col;
    }

    /**
     * Sets the value of the col property.
     * 
     */
    public void setCol(int value) {
        this.col = value;
    }

    /**
     * Gets the value of the rowSpan property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getRowSpan() {
        if (rowSpan == null) {
            return  1;
        } else {
            return rowSpan;
        }
    }

    /**
     * Sets the value of the rowSpan property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRowSpan(Integer value) {
        this.rowSpan = value;
    }

    /**
     * Gets the value of the colSpan property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getColSpan() {
        if (colSpan == null) {
            return  1;
        } else {
            return colSpan;
        }
    }

    /**
     * Sets the value of the colSpan property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setColSpan(Integer value) {
        this.colSpan = value;
    }

}
