//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.23 at 05:32:05 PM MEZ 
//


package eu.transkribus.core.model.beans.pagecontent;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import eu.transkribus.core.model.beans.pagecontent_trp.TrpRegionType;


/**
 * 
 * 				Pure text is represented as a text region. This includes
 * 				drop capitals, but practically ornate text may be
 * 				considered as a graphic.
 * 			
 * 
 * <p>Java class for TextRegionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TextRegionType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schema.primaresearch.org/PAGE/gts/pagecontent/2013-07-15}RegionType">
 *       &lt;sequence>
 *         &lt;element name="TextLine" type="{http://schema.primaresearch.org/PAGE/gts/pagecontent/2013-07-15}TextLineType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TextEquiv" type="{http://schema.primaresearch.org/PAGE/gts/pagecontent/2013-07-15}TextEquivType" minOccurs="0"/>
 *         &lt;element name="TextStyle" type="{http://schema.primaresearch.org/PAGE/gts/pagecontent/2013-07-15}TextStyleType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="orientation" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="type" type="{http://schema.primaresearch.org/PAGE/gts/pagecontent/2013-07-15}TextTypeSimpleType" />
 *       &lt;attribute name="leading" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="readingDirection" type="{http://schema.primaresearch.org/PAGE/gts/pagecontent/2013-07-15}ReadingDirectionSimpleType" />
 *       &lt;attribute name="readingOrientation" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="indented" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="align" type="{http://schema.primaresearch.org/PAGE/gts/pagecontent/2013-07-15}AlignSimpleType" />
 *       &lt;attribute name="primaryLanguage" type="{http://schema.primaresearch.org/PAGE/gts/pagecontent/2013-07-15}LanguageSimpleType" />
 *       &lt;attribute name="secondaryLanguage" type="{http://schema.primaresearch.org/PAGE/gts/pagecontent/2013-07-15}LanguageSimpleType" />
 *       &lt;attribute name="primaryScript" type="{http://schema.primaresearch.org/PAGE/gts/pagecontent/2013-07-15}ScriptSimpleType" />
 *       &lt;attribute name="secondaryScript" type="{http://schema.primaresearch.org/PAGE/gts/pagecontent/2013-07-15}ScriptSimpleType" />
 *       &lt;attribute name="production" type="{http://schema.primaresearch.org/PAGE/gts/pagecontent/2013-07-15}ProductionSimpleType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TextRegionType", propOrder = {
    "textLine",
    "textEquiv",
    "textStyle"
})
public class TextRegionType
    extends TrpRegionType
{

    @XmlElement(name = "TextLine")
    protected List<TextLineType> textLine;
    @XmlElement(name = "TextEquiv")
    protected TextEquivType textEquiv;
    @XmlElement(name = "TextStyle")
    protected TextStyleType textStyle;
    @XmlAttribute
    protected Float orientation;
    @XmlAttribute
    protected TextTypeSimpleType type;
    @XmlAttribute
    protected Integer leading;
    @XmlAttribute
    protected ReadingDirectionSimpleType readingDirection;
    @XmlAttribute
    protected Float readingOrientation;
    @XmlAttribute
    protected Boolean indented;
    @XmlAttribute
    protected AlignSimpleType align;
    @XmlAttribute
    protected LanguageSimpleType primaryLanguage;
    @XmlAttribute
    protected LanguageSimpleType secondaryLanguage;
    @XmlAttribute
    protected ScriptSimpleType primaryScript;
    @XmlAttribute
    protected ScriptSimpleType secondaryScript;
    @XmlAttribute
    protected ProductionSimpleType production;

    /**
     * Gets the value of the textLine property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the textLine property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTextLine().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextLineType }
     * 
     * 
     */
    public List<TextLineType> getTextLine() {
        if (textLine == null) {
            textLine = new ArrayList<TextLineType>();
        }
        return this.textLine;
    }

    /**
     * Gets the value of the textEquiv property.
     * 
     * @return
     *     possible object is
     *     {@link TextEquivType }
     *     
     */
    public TextEquivType getTextEquiv() {
        return textEquiv;
    }

    /**
     * Sets the value of the textEquiv property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextEquivType }
     *     
     */
    public void setTextEquiv(TextEquivType value) {
        this.textEquiv = value;
    }

    /**
     * Gets the value of the textStyle property.
     * 
     * @return
     *     possible object is
     *     {@link TextStyleType }
     *     
     */
    public TextStyleType getTextStyle() {
        return textStyle;
    }

    /**
     * Sets the value of the textStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextStyleType }
     *     
     */
    public void setTextStyle(TextStyleType value) {
        this.textStyle = value;
    }

    /**
     * Gets the value of the orientation property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getOrientation() {
        return orientation;
    }

    /**
     * Sets the value of the orientation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setOrientation(Float value) {
        this.orientation = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link TextTypeSimpleType }
     *     
     */
    public TextTypeSimpleType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextTypeSimpleType }
     *     
     */
    public void setType(TextTypeSimpleType value) {
        this.type = value;
    }

    /**
     * Gets the value of the leading property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLeading() {
        return leading;
    }

    /**
     * Sets the value of the leading property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLeading(Integer value) {
        this.leading = value;
    }

    /**
     * Gets the value of the readingDirection property.
     * 
     * @return
     *     possible object is
     *     {@link ReadingDirectionSimpleType }
     *     
     */
    public ReadingDirectionSimpleType getReadingDirection() {
        return readingDirection;
    }

    /**
     * Sets the value of the readingDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReadingDirectionSimpleType }
     *     
     */
    public void setReadingDirection(ReadingDirectionSimpleType value) {
        this.readingDirection = value;
    }

    /**
     * Gets the value of the readingOrientation property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getReadingOrientation() {
        return readingOrientation;
    }

    /**
     * Sets the value of the readingOrientation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setReadingOrientation(Float value) {
        this.readingOrientation = value;
    }

    /**
     * Gets the value of the indented property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIndented() {
        return indented;
    }

    /**
     * Sets the value of the indented property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIndented(Boolean value) {
        this.indented = value;
    }

    /**
     * Gets the value of the align property.
     * 
     * @return
     *     possible object is
     *     {@link AlignSimpleType }
     *     
     */
    public AlignSimpleType getAlign() {
        return align;
    }

    /**
     * Sets the value of the align property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlignSimpleType }
     *     
     */
    public void setAlign(AlignSimpleType value) {
        this.align = value;
    }

    /**
     * Gets the value of the primaryLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link LanguageSimpleType }
     *     
     */
    public LanguageSimpleType getPrimaryLanguage() {
        return primaryLanguage;
    }

    /**
     * Sets the value of the primaryLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link LanguageSimpleType }
     *     
     */
    public void setPrimaryLanguage(LanguageSimpleType value) {
        this.primaryLanguage = value;
    }

    /**
     * Gets the value of the secondaryLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link LanguageSimpleType }
     *     
     */
    public LanguageSimpleType getSecondaryLanguage() {
        return secondaryLanguage;
    }

    /**
     * Sets the value of the secondaryLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link LanguageSimpleType }
     *     
     */
    public void setSecondaryLanguage(LanguageSimpleType value) {
        this.secondaryLanguage = value;
    }

    /**
     * Gets the value of the primaryScript property.
     * 
     * @return
     *     possible object is
     *     {@link ScriptSimpleType }
     *     
     */
    public ScriptSimpleType getPrimaryScript() {
        return primaryScript;
    }

    /**
     * Sets the value of the primaryScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScriptSimpleType }
     *     
     */
    public void setPrimaryScript(ScriptSimpleType value) {
        this.primaryScript = value;
    }

    /**
     * Gets the value of the secondaryScript property.
     * 
     * @return
     *     possible object is
     *     {@link ScriptSimpleType }
     *     
     */
    public ScriptSimpleType getSecondaryScript() {
        return secondaryScript;
    }

    /**
     * Sets the value of the secondaryScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScriptSimpleType }
     *     
     */
    public void setSecondaryScript(ScriptSimpleType value) {
        this.secondaryScript = value;
    }

    /**
     * Gets the value of the production property.
     * 
     * @return
     *     possible object is
     *     {@link ProductionSimpleType }
     *     
     */
    public ProductionSimpleType getProduction() {
        return production;
    }

    /**
     * Sets the value of the production property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductionSimpleType }
     *     
     */
    public void setProduction(ProductionSimpleType value) {
        this.production = value;
    }

}
