//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.19 at 03:32:22 PM CET 
//


package eu.transkribus.core.model.beans.fat;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.dea.transcript.trp.core.model.beans.fat package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.dea.transcript.trp.core.model.beans.fat
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link File }
     * 
     */
    public File createFile() {
        return new File();
    }

    /**
     * Create an instance of {@link RootFolder }
     * 
     */
    public RootFolder createRootFolder() {
        return new RootFolder();
    }

    /**
     * Create an instance of {@link SubFolder }
     * 
     */
    public SubFolder createSubFolder() {
        return new SubFolder();
    }

    /**
     * Create an instance of {@link DocumentFolder }
     * 
     */
    public DocumentFolder createDocumentFolder() {
        return new DocumentFolder();
    }

    /**
     * Create an instance of {@link Order }
     * 
     */
    public Order createOrder() {
        return new Order();
    }

    /**
     * Create an instance of {@link OcrMetadata }
     * 
     */
    public OcrMetadata createOcrMetadata() {
        return new OcrMetadata();
    }

    /**
     * Create an instance of {@link FepMetadata }
     * 
     */
    public FepMetadata createFepMetadata() {
        return new FepMetadata();
    }

    /**
     * Create an instance of {@link FileFolder }
     * 
     */
    public FileFolder createFileFolder() {
        return new FileFolder();
    }

    /**
     * Create an instance of {@link File.Metadata }
     * 
     */
    public File.Metadata createFileMetadata() {
        return new File.Metadata();
    }

}
