//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.19 at 03:32:22 PM CET 
//


package eu.transkribus.core.model.beans.fat;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.literature.at/schemas/FAT/FAT_1.1.xsd}OcrMetadata"/>
 *         &lt;element ref="{http://www.literature.at/schemas/FAT/FAT_1.1.xsd}FepMetadata" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="HasViewingFiles" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="Services" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ocrMetadata",
    "fepMetadata"
})
@XmlRootElement(name = "Order")
public class Order {

    @XmlElement(name = "OcrMetadata", required = true)
    protected OcrMetadata ocrMetadata;
    @XmlElement(name = "FepMetadata")
    protected FepMetadata fepMetadata;
    @XmlAttribute(name = "HasViewingFiles", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String hasViewingFiles;
    @XmlAttribute(name = "Services", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String services;

    /**
     * Gets the value of the ocrMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link OcrMetadata }
     *     
     */
    public OcrMetadata getOcrMetadata() {
        return ocrMetadata;
    }

    /**
     * Sets the value of the ocrMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link OcrMetadata }
     *     
     */
    public void setOcrMetadata(OcrMetadata value) {
        this.ocrMetadata = value;
    }

    /**
     * Gets the value of the fepMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link FepMetadata }
     *     
     */
    public FepMetadata getFepMetadata() {
        return fepMetadata;
    }

    /**
     * Sets the value of the fepMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link FepMetadata }
     *     
     */
    public void setFepMetadata(FepMetadata value) {
        this.fepMetadata = value;
    }

    /**
     * Gets the value of the hasViewingFiles property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHasViewingFiles() {
        return hasViewingFiles;
    }

    /**
     * Sets the value of the hasViewingFiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHasViewingFiles(String value) {
        this.hasViewingFiles = value;
    }

    /**
     * Gets the value of the services property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServices() {
        return services;
    }

    /**
     * Sets the value of the services property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServices(String value) {
        this.services = value;
    }

}
